/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("EmissionRecordListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheEmissionRecordListGenerated.iSeeThisPage();
        });


        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheEmissionRecordListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheEmissionRecordListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheEmissionRecordListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheEmissionRecordListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheEmissionRecordListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheEmissionRecordListGenerated.onTable(defaultTableId).iCheckCreate({ visible: true });
            // When.onTheEmissionRecordListGenerated.onTable(defaultTableId).iPressCreate();
            // When.onTheEmissionRecordListGenerated.onTable(defaultTableId).iPressDelete();
            Then.onTheEmissionRecordListGenerated.onTable(defaultTableId).iCheckDelete({ visible: true });
            // When.onTheEmissionRecordListGenerated.onTable(defaultTableId).iPressAction("Submit");
            Then.onTheEmissionRecordListGenerated.onTable(defaultTableId).iCheckAction("Submit", { enabled: false });
            // When.onTheEmissionRecordListGenerated.onTable(defaultTableId).iPressAction("Approve");
            Then.onTheEmissionRecordListGenerated.onTable(defaultTableId).iCheckAction("Approve", { enabled: false });
            // When.onTheEmissionRecordListGenerated.onTable(defaultTableId).iPressAction("Reject");
            Then.onTheEmissionRecordListGenerated.onTable(defaultTableId).iCheckAction("Reject", { enabled: false });
            // When.onTheEmissionRecordListGenerated.onTable(defaultTableId).iPressAction("Generate Report");
            Then.onTheEmissionRecordListGenerated.onTable(defaultTableId).iCheckAction("Generate Report", { enabled: false });
            Then.onTheEmissionRecordListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"FacilityId":{"header":"Facility"},"ReportingPeriod":{"header":"Reporting Period"},"Scope":{"header":"Scope"},"Status":{"header":"Status"},"TotalCO2e":{"header":"Total CO2e"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheEmissionRecordListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheEmissionRecordListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheEmissionRecordListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheEmissionRecordObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});