/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("EmissionRecordObjectPageObjectPage journey");

        opaTest("Navigate to EmissionRecordObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheEmissionRecordListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheEmissionRecordListGenerated.onTable().iCheckRows();
            When.onTheEmissionRecordListGenerated.onTable().iPressRow(0);

            Then.onTheEmissionRecordObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheEmissionRecordObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onTheEmissionRecordObjectPageGenerated.onHeader().iPressEdit();
            Then.onTheEmissionRecordObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zui_esg_emissionrecord.v0001", action: "generateReport", unbound: false } /* , { enabled: true } */);
            // When.onTheEmissionRecordObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zui_esg_emissionrecord.v0001", action: "generateReport", unbound: false });
            Then.onTheEmissionRecordObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zui_esg_emissionrecord.v0001", action: "rejectRecord", unbound: false } /* , { enabled: true } */);
            // When.onTheEmissionRecordObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zui_esg_emissionrecord.v0001", action: "rejectRecord", unbound: false });
            Then.onTheEmissionRecordObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zui_esg_emissionrecord.v0001", action: "approveRecord", unbound: false } /* , { enabled: true } */);
            // When.onTheEmissionRecordObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zui_esg_emissionrecord.v0001", action: "approveRecord", unbound: false });
            Then.onTheEmissionRecordObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zui_esg_emissionrecord.v0001", action: "submitRecord", unbound: false } /* , { enabled: true } */);
            // When.onTheEmissionRecordObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zui_esg_emissionrecord.v0001", action: "submitRecord", unbound: false });
        });


        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheEmissionRecordObjectPageGenerated.iCheckNumberOfSections(2);
        });

        opaTest("Check the HeaderInfo section of the Object Page", function (_Given, When, Then) {
            When.onTheEmissionRecordObjectPageGenerated.iPressSectionIconTabFilterButton("HeaderInfo");
            Then.onTheEmissionRecordObjectPageGenerated.iCheckSection({ section: "HeaderInfo" });
            Then.onTheEmissionRecordObjectPageGenerated.onForm({ section: "HeaderInfo" }).iCheckField({ property: "FacilityId" });
            Then.onTheEmissionRecordObjectPageGenerated.onForm({ section: "HeaderInfo" }).iCheckField({ property: "ReportingPeriod" });
            Then.onTheEmissionRecordObjectPageGenerated.onForm({ section: "HeaderInfo" }).iCheckField({ property: "Scope" });
            Then.onTheEmissionRecordObjectPageGenerated.onForm({ section: "HeaderInfo" }).iCheckField({ property: "Status" });
            Then.onTheEmissionRecordObjectPageGenerated.onForm({ section: "HeaderInfo" }).iCheckField({ property: "TotalCO2e" });
        });

        opaTest("Check the ItemsFacet section of the Object Page", function (_Given, When, Then) {
            When.onTheEmissionRecordObjectPageGenerated.iPressSectionIconTabFilterButton("ItemsFacet");
            Then.onTheEmissionRecordObjectPageGenerated.iCheckSection({ section: "ItemsFacet" });
            Then.onTheEmissionRecordObjectPageGenerated.onTable({ property: "_Items" }).iCheckColumns(undefined, {"AssetId":{"header":"AssetId"},"ActivityType":{"header":"ActivityType"},"Quantity":{"header":"Quantity"},"Unit":{"header":"Unit"},"CO2e":{"header":"CO2e"}});
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});